param(
  [Parameter(Mandatory = $true)]
  [string]$FfmpegExePath,
  [Parameter(Mandatory = $true)]
  [string]$Version,
  [Parameter(Mandatory = $true)]
  [string]$SourceName,
  [Parameter(Mandatory = $true)]
  [string]$SourceUrl,
  [string]$License = "LGPL-2.1-or-later"
)

$ErrorActionPreference = "Stop"

$targetDir = Split-Path -Parent $PSCommandPath
$targetExe = Join-Path $targetDir "ffmpeg.exe"
$provenancePath = Join-Path $targetDir "ffmpeg-provenance.json"

Copy-Item -Path $FfmpegExePath -Destination $targetExe -Force
$hash = (Get-FileHash -Path $targetExe -Algorithm SHA256).Hash.ToLowerInvariant()

$payload = [ordered]@{
  sourceName = $SourceName
  sourceUrl = $SourceUrl
  version = $Version
  license = $License
  sha256 = $hash
  fetchedAt = (Get-Date).ToString("yyyy-MM-dd")
  notes = "Generated by update_ffmpeg_bundle.ps1"
}

$payload | ConvertTo-Json | Set-Content -Path $provenancePath -NoNewline -Encoding UTF8

Write-Host "Bundled ffmpeg updated: $targetExe"
Write-Host "SHA256: $hash"
